### ISSUE TITLE
Testing a package in CI mode - never exits

### ISSUE THREAD

**Issue by matfin** [meteor-velocity/velocity-cli#2]
To test a package I am writing, I am running the following command (on my local development environment):

```
velocity test-package my-package --ci
```

I get the following back

```
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
I20150807-14:46:44.107(2)? [velocity] is in continuous integration mode
=> Started your app.

=> App running at: http://localhost:3000/
PASSED jasmine-server-integration : init():Collections  => should set up the collections
PASSED jasmine-server-integration : updateToCollection():Collections  => should throw a Meteor error if the collection cannot be found given the name
and so on for the next 41 tests.
```

What I would expect is that the above command would exit as soon as all the tests have completed their run. This, from my understanding, is what the --ci flag is for.

What is actually happening is that the test runner stays open and active. This means I cannot deploy this to Travis CI because it does not exit after ten minutes and then the build fails. 

Details of my platform are as follows
- MacOSX Yosemite
- Node v0.12.7

The package can be seen on [GitHub](https://github.com/matfin/meteor-contentful/tree/develop)

**Comment by ghost** [comment]
Can you update to velocity-cli@0.3.3 please and see if you get an error from PhantomJS in the console.

**Comment by ghost** [comment]
You need to run the tests like this:

```
JASMINE_CLIENT_INTEGRATION=0 velocity test-package ./ --ci
```

It waits for client integration tests, but there are no client integration tests. I will create an issue for this and fix it in sanjo:jasmine.

**Comment by matfin** [comment]
Hey,

Just uninstalled velocity-cli and installed velocity-cli@0.3.3 - same, as I was using the same versions (only installed it for the first time this morning).

It doesn't look like there was any errors - all tests appear to be running and passing too.

Interestingly enough, when I ran the following command:

```
VELOCITY_TEST_PACKAGES=1 meteor test-packages --once --driver-package velocity:console-reporter --velocity --release velocity:METEOR@1.1.0.3_1 ./
```

It seems to go one step further and I see the following at the end of my tests:

```
PASSED jasmine-server-integration : assetChanged():ImageProcessor  => should push an updated asset to the queue with a create task and then run the queue
PASSED jasmine-server-integration : assetRemoved():ImageProcessor  => should throw when an invalid asset is removed
PASSED jasmine-server-integration : assetRemoved():ImageProcessor  => should push a removed asset to the queue with a delete task and then run the queue
I20150807-15:09:57.607(2)? jasmine-server-integration: *41 tests passed* (675ms)
```

What I did was change velocity:html-reporter for velocity:console-reporter.

If you want to see my build running - check it out at https://travis-ci.org/matfin/meteor-contentful/builds/74566114

I am using Travis CI - the build file is as follows:

```
# The language specific base vm to use for this repository
language: node_js

# The node.js version to install
node_js: "0.12.7"

install:
  # Install meteor
  - "curl https://install.meteor.com | /bin/sh"
  # Adding meteor to the $PATH
  - "export PATH=$HOME/.meteor:$PATH"
  # Install the velocity cli tool
  - "npm install velocity-cli"

# For testing meteor packages, that's all that is needed. 
script:
  - "VELOCITY_TEST_PACKAGES=1 meteor test-packages --once --driver-package velocity:console-reporter --velocity --release velocity:METEOR@1.1.0.3_1 ./"
```

**Comment by matfin** [comment]
That seems to have done it. It exited on the console on my local dev environment - will try on Travis now.

**Comment by ghost** [comment]
Alternative fix: https://github.com/Sanjo/meteor-jasmine/issues/261#issuecomment-128699801
