### ISSUE TITLE
Tests only run on Chrome, and only if clicking "DEBUG"

### ISSUE THREAD

**Issue by gmsecrieru** [meteor-velocity/velocity-cli#4]
Hi,

I have tried several things to get [RocketChat application tests](https://github.com/RocketChat/Rocket.Chat/pull/1045) to run on PhantomJS but had no luck so far. I managed to run them on Chrome but with a very strange behavior: jasmine-client-unit only run when I hit "DEBUG" button:
![screen shot 2015-10-09 at 12 28 04](https://cloud.githubusercontent.com/assets/190883/10398061/4eb58efa-6e81-11e5-9fe2-50574498d317.png)

`JASMINE_DEBUG=1 VELOCITY_DEBUG=1 velocity test-app --ci`
![screen shot 2015-10-09 at 12 21 39](https://cloud.githubusercontent.com/assets/190883/10397888/611824aa-6e80-11e5-81cc-648671bd1f64.png)

The bottom lines of the logs appear when I hit the debug button "Debug":

``` bash
I20151009-12:21:32.422(-3)? [publish] settings
I20151009-12:21:32.500(-3)? [publish] permissions
PASSED jasmine-client-unit : App | Client | Lib | SideNav => should exist
I20151009-12:21:32.939(-3)? jasmine-client-unit: 1 tests passed (5ms)
TESTS RAN SUCCESSFULLY
Georges-MacBook:RocketChat gmsecrieru$ 
```

I have the feeling that PhantomJS execution is not working for the same reason. Any thoughts on how to bypass this?

Thanks!

**Comment by ghost** [comment]
Try `meteor update sanjo:jasmine`. If that doesn't help, please tell me the version of sanjo:jasmine and Meteor that you use.

**Comment by gmsecrieru** [comment]
Hi @Sanjo, thanks for the quick reply!

I've tried updating but no luck. Console output:

``` bash
Georges-MacBook:RocketChat gmsecrieru$ meteor update sanjo:jasmine
The specified packages are at their latest compatible versions.
Georges-MacBook:RocketChat gmsecrieru$ meteor --version
Meteor 1.2.0.2
Georges-MacBook:RocketChat gmsecrieru$ 
```

`.meteor/local/log/jasmine-client-unit.log` can be seen [here](https://gist.github.com/gmsecrieru/2fd9d80743054512ebeb)

From the bottom lines looks like the `context.html` file is unavailable:

``` bash
[33m09 10 2015 12:27:38.544:WARN [karma]: [39mNo captured browser, open http://localhost:9876/
[32m09 10 2015 12:27:38.565:INFO [karma]: [39mKarma v0.13.9 server started at http://localhost:9876/
[32m09 10 2015 12:27:38.625:INFO [launcher]: [39mStarting browser Chrome
[32m09 10 2015 12:27:49.413:INFO [Chrome 45.0.2454 (Mac OS X 10.10.5)]: [39mConnected on socket oFtEzJMSOgUdyDubAAAA with id 33539803
[33m09 10 2015 12:27:53.230:WARN [web-server]: [39m404: /_timesync
Chrome 45.0.2454 (Mac OS X 10.10.5) LOG: 'Error syncing to server time: ', Error{response: Object{statusCode: 404, content: 'NOT FOUND', headers: Object{connection: ..., date: ..., transfer-encoding: ...}, data: null}}

[33m09 10 2015 12:27:54.264:WARN [web-server]: [39m404: /_timesync
Chrome 45.0.2454 (Mac OS X 10.10.5) LOG: 'Error syncing to server time: ', Error{response: Object{statusCode: 404, content: 'NOT FOUND', headers: Object{connection: ..., date: ..., transfer-encoding: ...}, data: null}}

Chrome 45.0.2454 (Mac OS X 10.10.5) ERROR: 'There is no route for the path:', '/context.html'

[33m09 10 2015 12:27:55.538:WARN [web-server]: [39m404: /_timesync
Chrome 45.0.2454 (Mac OS X 10.10.5) ERROR
  Uncaught TypeError: ServiceConfiguration.configurations.find is not a function
  at /Users/gmsecrieru/Projects/RocketChat/.meteor/local/build/programs/web.browser/app/client/views/login/services.coffee.js:11


[33m09 10 2015 12:30:17.943:WARN [web-server]: [39m404: /_timesync
[33m09 10 2015 12:30:19.659:WARN [web-server]: [39m404: /_timesync
[33m09 10 2015 12:30:20.668:WARN [web-server]: [39m404: /_timesync
[33m09 10 2015 12:30:21.675:WARN [web-server]: [39m404: /_timesync
[33m09 10 2015 12:30:22.682:WARN [web-server]: [39m404: /_timesync
Parent process ( 68409 ) is dead! Exiting jasmine-client-unit
```

**Comment by gmsecrieru** [comment]
Running sanjo:jasmine@0.20.2

**Comment by ghost** [comment]
I think the breaking error is

> Chrome 45.0.2454 (Mac OS X 10.10.5) ERROR
>   Uncaught TypeError: ServiceConfiguration.configurations.find is not a function
>   at /Users/gmsecrieru/Projects/RocketChat/.meteor/local/build/programs/web.browser/app/client/views/login/services.coffee.js:11

Can you log what `ServiceConfiguration.configurations` is at the failing line. It must be something but not a Mongo collection as expected.

---

To "fix" the routing error, you need to disable your router in client unit mode. If you tell me what router you use, I can eventually do this by default. Currently I only handle this for iron:router.

**Comment by gmsecrieru** [comment]
Thanks again!  We are using [Flow Router](https://github.com/kadirahq/flow-router). 

I will look for the `ServiceConfiguration.configurations`, might be something that needs to be initialized somewhere else.

**Comment by gmsecrieru** [comment]
I commented out that piece of code and indeed it was the problem, as now I can run test with both Chrome and PhantomJS:

Chrome
![screen shot 2015-10-09 at 13 22 55](https://cloud.githubusercontent.com/assets/190883/10399412/f89a901c-6e88-11e5-9394-d007eaed9979.png)

PhantomJS
![screen shot 2015-10-09 at 13 26 08](https://cloud.githubusercontent.com/assets/190883/10399491/5e5dfdda-6e89-11e5-828d-23a4d6432404.png)

Thanks for your time!
