### ISSUE TITLE
Environment variables like JASMINE_CLIENT_INTEGRATION=0 are not passed to spawn process

### ISSUE THREAD

**Issue by wheeler** [meteor-velocity/velocity-cli#6]
To reproduce:
- Run velocity CLI with environment variables like this:
  
  ``` shell
  JASMINE_CLIENT_UNIT=0 JASMINE_CLIENT_INTEGRATION=0 velocity test-packages some-package
  ```
- Jasmine client tests will still run.

Workaround: comment out all client tests.

**Comment by ghost** [comment]
Those flags doesn't work in the package testing mode. You can use xdescribe to disable some tests.

**Comment by wheeler** [comment]
Why not?

**Comment by ghost** [comment]
What is your use case? Why do you want to disable the client tests for a package test run?

**Comment by wheeler** [comment]
Lets say I have many tests, both Jasmine Server Integration and Jasmine Client Integration.

If I'm investigating a particular Jasmine server test I might put `fdescribe` on it to focus it and run only that one test. With Velocity CLI this will focus the test only among the server integration tests and still run all the client integration tests. (That may be considered a general meteor:jasmine problem). The goal was to focus the test for quick results cycles while working on it. As a workaround you would think `JASMINE_CLIENT_INTEGRATION=0` would stop all client tests since it does in other ways of running Velocity tests.

It's also just nice to have be able to have fewer mirrors running sometimes since they are resource intensive.

If there was a way to truly focus a single test across mirrors (either in code or in the html-reporter) this wouldn't be as necessary, but it still seems inconsistent.

**Comment by ghost** [comment]
Ok. I see. I track this issue here: https://github.com/xolvio/meteor-jasmine/issues/299.

For package testing the client and server tests run in the same mirror sequentially.
